baseURL = 'https://example.org/'
languageCode = 'en-us'
title = "Thunder's Website"
siteBanner= 'images/banner.jpg'
theme = 'rusty-typewriter'
enableEmoji = true

[taxonomies]
  tag = 'tags'
  category = 'categories'

[params.rtwt]
  sidePane = true
  countPageItems = 7

[params.rtwt.home]
  showBio = true
  showAuthorImg = true
  showHomeBanner = true
  sidePaneTags = true
  showFeatured = true
  showRecent = true
  hideRecentWhenFeatured = true
  countRecent = 5

[params.rtwt.side.home]
  sidePaneSticky = false
  taxonomies = ['tags']
  countTaxonomy = 5

[params.rtwt.side.single]
  sidePaneSticky = true
  showDetails = true
  showTableOfContents = true
  showAttachments = true
  showRelated = true
  countRelated = 5


[menu]
  [[menu.main]]
      name = "About"
      url = "/about"
      weight = 10

  [[menu.main]]
      name = "Resumé"
      url = "/resume"
      weight = 20

  # [[menu.main]]
  #     name = "Resumé"
  #     url = "/r2"
  #     weight = 20

  [[menu.main]]
      name = "Posts"
      url = "/posts"
      weight = 20
  
  [[menu.main]]
    name = "Socials"
    url = "/socials"
    weight = 40