baseURL = 'https://example.org/'
languageCode = 'en-us'
title = "Thunderized"
theme = "hugo-coder"
enableEmoji = true

[markup.highlight]
style = "github-dark"

[params]
  author = "Navneet Dubey"
  info = "Computer Science Student"
  description = "Navneet's personal website"
  keywords = "blog,developer,personal"
  dateFormat = "January 1, 2000"
  avatarurl = "images/avatar.jpg"

  faviconSVG = "/img/favicon.svg"
  favicon_32 = "/img/favicon-32x32.png"
  favicon_16 = "/img/favicon-16x16.png"

  since = 2024
  # license = '<a rel="license" href="http://creativecommons.org/licenses/by-sa/4.0/">CC BY-SA-4.0</a>'
  rss = '<a rel="RSS" href="/index.xml">RSS</a>'

  enableTwemoji = true

  colorScheme = "auto"
  hidecolorschemetoggle = false

[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"
  author = "authors"

# Social links
[[params.social]]
  name = "Github"
  icon = "fa-brands fa-github fa-2x"
  weight = 1
  url = "https://github.com/ThunderE75"
[[params.social]]
  name = "Linkedin"
  icon = "fa-brands fa-linkedin fa-2x"
  weight = 2
  url = "https://www.linkedin.com/in/navneet-prakash-dubey/"
[[params.social]]
  name = "Leetcode"
  icon = "fa-solid fa-code fa-2x"
  weight = 2
  url = "https://leetcode.com/u/ThunderE75/"
[[params.social]]
  name = "Bluesky"
  icon = "fa-brands fa-bluesky fa-2x"
  weight = 2
  url = "https://bsky.app/profile/thunder75.bsky.social"
[[params.social]]
  name = "Twitter"
  icon = "fa-brands fa-x-twitter fa-2x"
  weight = 3
  url = "https://x.com/navneet_dubey_"
[[params.social]]
  name = "Peerlist"
  icon = "fa-solid fa-p fa-2x"
  weight = 3
  url = "https://peerlist.io/thunder"

# Menu links
[[menu.main]]
  name = "Blog"
  weight = 1
  url  = "posts/"
[[menu.main]]
  name = "Resumé"
  weight = 1
  url  = "resume/"
[[menu.main]]
  name = "About"
  weight = 2
  url = "about/"